In [2]:
import numpy as np
import matplotlib.pyplot as plt
#ignore warning message
import warnings
warnings.filterwarnings('ignore')

In [21]:
#1
list = [2,-1,3]
result = list*4
result


[2, -1, 3, 2, -1, 3, 2, -1, 3, 2, -1, 3]

In [22]:
list_2 = np.array([2,-1,3])
res = list_2 * 4

In [ ]:
#because the list just repeats it by scalar time, numpy array multiplies it by scalar

In [18]:
#2
a = np.array([5,-3])
lam = -2 
lambda_a = lam * a
print("λa =", lambda_a)
mag_a = np.sqrt(a[0]**2 + a[1]**2)
mag_lambda_a = np.sqrt(lambda_a[0]**2 + lambda_a[1]**2)

print("a =", a)
print("λa =", lambda_a)

print("\n|a| =", mag_a)
print("|λa| =", mag_lambda_a)

# plot them
plt.plot([0, a[0]],[0, a[1]],'k',label='a')
plt.plot([0, a_sc[0]],[0, a_sc[1]],'r--',label='$\lambda a$')
plt.legend()
plt.axis('square')
axlim = max([max(abs(a)),max(abs(a_sc))])*1.5 # dynamic axis lim
plt.axis((-axlim,axlim,-axlim,axlim))
plt.grid()
plt.show()


λa = [-10   6]
a = [ 5 -3]
λa = [-10   6]

|a| = 5.830951894845301
|λa| = 11.661903789690601


In [ ]:
Magnitude: increases by factor ∣𝜆∣=2
Direction: reversed because 𝜆<0

In [19]:
#3 Column vector (3,1)
col = np.array([[1],
                [2],
                [3]])

# Row vector (1,4)
row = np.array([[10, 20, 30, 40]])


result = col + row

# Print shapes
print("Column shape:", col.shape)
print("Row shape:", row.shape)
print("Result:\n", result)
print("Result shape:", result.shape)

Column shape: (3, 1)
Row shape: (1, 4)
Result:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
Result shape: (3, 4)


In [23]:
#4
v = np.array([1, 2, 3, 4])
result = v + 5
print(result)
print(result.shape)

[6 7 8 9]
(4,)


In [ ]:
NumPy allows this because of broadcasting: it automatically expands the scalar to match the vector’s shape.
Then it performs element-wise addition to each element of the vector.

In [4]:
#5
a = np.array([1, 2, 3, 4, 5, 6])

#1.Manual 
a = np.array([1,2,3,4,5,6])
norm = np.sqrt(np.sum(a*a))

#2. Using NumPy function
norm_numpy = np.linalg.norm(a)


print("Euclidean norm (manual):", norm)
print("\nNumPy norm:", norm_numpy)

Euclidean norm (manual): 9.539392014169456

NumPy norm: 9.539392014169456


In [25]:
#6
# generate random vector
v = np.random.rand(10)

# norm before
norm_before = np.sqrt(np.sum(v**2))

# normalize
v_normalized = v / norm_before

# norm after
norm_after = np.sqrt(np.sum(v_normalized**2))

print("Vector:", v)
print("\nNorm before:", norm_before)

print("\nNormalized vector:", v_normalized)
print("Norm after:", norm_after)

Vector: [0.18168666 0.74513635 0.7073372  0.02634578 0.90072873 0.13399819
 0.20729528 0.02470278 0.31346546 0.82691514]

Norm before: 1.6565496702971731

Normalized vector: [0.10967776 0.44981226 0.42699426 0.01590401 0.54373784 0.08088993
 0.12513677 0.01491219 0.18922793 0.4991792 ]
Norm after: 1.0


In [27]:
#7
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([0, -4, 3, -3, 6, 5])

#1.Manual loop
dot_manual = 0
for i in range(len(a)):
    dot_manual += a[i] * b[i]

#2.NumPy
dot_numpy = np.dot(a, b)

print("Manual dot product:", dot_manual)
print("NumPy dot product:", dot_numpy)

Manual dot product: 49
NumPy dot product: 49


In [ ]:
The dot product is computed as the sum of element-wise multiplications.
Both manual loop and NumPy give the same result: 49.

In [28]:
#8
#generate random vectors (length 3)
a = np.random.rand(3)
b = np.random.rand(3)
c = np.random.rand(3)

# left side
left = np.dot(a, b + c)

# right side
right = np.dot(a, b) + np.dot(a, c)

print("a:", a)
print("b:", b)
print("c:", c)

print("\nLeft side a·(b+c):", left)
print("Right side a·b + a·c:", right)

print("\nAre they equal?", np.isclose(left, right))

a: [0.54485065 0.36299652 0.39229706]
b: [0.84352931 0.11095711 0.16994487]
c: [0.87789329 0.73247424 0.42759692]

Left side a·(b+c): 1.478494752694345
Right side a·b + a·c: 1.478494752694345

Are they equal? True


In [30]:
#9 Compute the Euclidean distance matrix between every point in group A and every point in group B.
# Group A (4,2)
A = np.array([
    [2, 1],
    [5, 4],
    [1, 6],
    [7, 2]
])

# Group B (3,2)
B = np.array([
    [0, 0],
    [6, 3],
    [3, 5]
])


A_expanded = A[:, np.newaxis, :]   # (4,1,2)
B_expanded = B[np.newaxis, :, :]   # (1,3,2)

diff = A_expanded - B_expanded

sq = diff ** 2

sum_sq = np.sum(sq, axis=2)

dist = np.sqrt(sum_sq)

print("Distance matrix:\n", dist)

Distance matrix:
 [[2.23606798 4.47213595 4.12310563]
 [6.40312424 1.41421356 2.23606798]
 [6.08276253 5.83095189 2.23606798]
 [7.28010989 1.41421356 5.        ]]
